### ISSUE TITLE
Вопрос по работе системы

### ISSUE THREAD

**Issue by warrior13reg** [va-stepanov/vosk-model-ru-adaptation#1]
Здравствуйте!

Подскажите, пжта, 

1. можно ли использовать вашу разработку для английского языка? Если да, то будет ли алгоритм тем же, что описан?
2.пробовали ли Вы передавать голос в формате 16 кГЦ? Если да, не могли бы подсказать с тонкостью в настройках? 

Заранее спасибо!

**Comment by va-stepanov** [comment]
Здравствуйте.

1. Если взять английские модели, аналогичные скрипты и сопутствующие файлы к моделям, а также заменить команды по обработке кириллицы на аналогичные для латиницы, то можно.
2. Передавать как и куда? Командной строкой kaldi я проверял на тестовом файле для русской модели, его формат я правда не помню. Но, думаю, он такой же, как и формат файлов, которые подаются vosk-серверу, через тот же веб-сокет.  По умолчанию это и есть 16 кГЦ PCM, с таким форматом я и работаю.
