### ISSUE TITLE
Ошибка при работе скрипта

### ISSUE THREAD

**Issue by somesomesomething** [va-stepanov/vosk-model-ru-adaptation#2]
Привет!

Спасибо за твою работу.

Решил расширить словарь по указаниям, но в процессе работы возникли ошибки. Передаю в контейнер докера файл corpus.txt , дальше ожидаю выполнение автоматического скрипта. После его завершения выполняю проверку тестового аудио. Происходит определение несколькоих слов и сразу получаю ошибку:

`websockets.exceptions.ConnectionClosedError: no close frame received or sent`

После попытки поднять сервер повторно:

`ERROR (VoskAPI:Model():model.cc:122) Folder 'model' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.`

Как я понимаю, у меня не происходит правильная сборка модели. В чём могут быть проблемы? Или как их возможно отследить? Возвращение исходной модели исправляет все ошибки.

**Comment by va-stepanov** [comment]
Привет!
У авторов VOSK появилась своя [статья](https://alphacephei.com/vosk/lm) со скриптами для адаптации, возможно будет полезной.
[Первое](https://github.com/aaugustin/websockets/blob/main/src/websockets/exceptions.py) похоже на ошибку работы с закрытым не должным образом соединением (или простаивающим).  Проверь, что клиентская часть отправляет сообщение о закрытии []byte("{\"eof\" : 1}").
[Второе](https://github.com/alphacep/vosk-api/blob/master/src/model.cc) связано с отсутствием необходимых файлов в заданном каталоге модели. 
Либо указывается каталог модели (model_path_str_), и от него должны быть доступны файлы:
model_path_str_ + "/am/final.mdl";
model_path_str_ + "/conf/mfcc.conf";
(либо
model_path_str_ + "/final.mdl";
model_path_str_ + "/mfcc.conf";)
Могу предположить, что при ручном запуске сервера ты забываешь указать в качестве параметра каталог модели, либо задаешь путь неверно.

**Comment by somesomesomething** [comment]
> Могу предположить, что при ручном запуске сервера ты забываешь указать в качестве параметра каталог модели, либо задаешь путь неверно

Вроде использую всё, как указано. 
Спасибо, попробую твои рекоммендации, посмотрю более внимательно что может быть с моделью

**Comment by va-stepanov** [comment]
У меня могут быть неточности, так что лучше понимать, что делаешь на каждом шаге.
Если ты используешь контейнер со скриптом update_corpus.sh, то ручного запуска сервера веб-сокета не должно быть.
Ведь этот скрипт и обновляет файлы и перестартовывает сервер. А завершенное соединение вроде бы не должно приводить к падению сервера веб-сокета. Но, если по каким-то причинам ты перезапускаешь вручную, то команда должна быть такой:
python3 /opt/vosk-server/websocket/asr_server.py /opt/vosk-model-ru/model
без амперсанда.
